"""Open-weights tier on Hugging Face Jobs — build, submit and recover (DEVIATIONS D2).

The GPU run uses the frozen r3 instrument through `harness-r3/run_open_r3.py`; nothing in this file
changes prompts, files, predicates or the analysis. The job script is self-contained (the harness files
are embedded byte-for-byte, so the plan's `source_hash` on the GPU machine equals the frozen one) and
brings its run directory back on three channels: an upload into the private dataset repo
`frnk/peer-traces-open-runs` (the default; needs `HF_TOKEN` as a job secret — decided 7 September: private
first, public after the login e-mail is scrubbed), a `/output` volume if one is mounted, and — always — the
proven channel of the Codex working package: base64 chunks of the tar.gz in the job log.

  python3 open_tier/hf_job.py build --name open-pilot --design tier --seed 80907 [--blocks 8] [--model Qwen/Qwen3-8B] [--revision SHA]
  python3 open_tier/hf_job.py submit open_tier/jobs/open-pilot.py [--flavor a10g-large] [--timeout 3h] [--repo frnk/peer-traces-open-runs] [--dry-run]
  python3 open_tier/hf_job.py recover <job_id> --into harness-r3/runs/open-pilot        # or: --log saved_log.txt
  python3 harness-r3/analyze_r3.py harness-r3/runs/open-pilot --design tier

Local end-to-end test of the packaging without a model:  python3 open_tier/jobs/open-pilot.py --backend stub
Submitting needs a logged-in `hf` CLI or HF_TOKEN in the environment; `--dry-run` prints the call instead. The dataset
upload needs a token with write access to repos (the 8 September pilot ran with a jobs-only token: `--repo ''`, archive
in the log). Do not pass environment variables whose value is `1` through the transport — the connector masks that
literal in the returned log (8 September); the job sets its own variables in Python.
Costs are the account's GPU minutes (flavor × wall time; a10g-large 1.50 USD/h on 8 September — the 32-episode pilot
took 4 minutes); the log records generation seconds per episode.
"""
import argparse
import base64
import hashlib
import io
import json
import os
import re
import sys
import tarfile
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
HARNESS = ROOT / "harness-r3"
EMBED = ("fixtures_r3.py", "workspace_server.py", "run_r3.py", "analyze_r3.py", "schema.py", "stats.py", "report.py",
         "run_open_r3.py", "concern_server.py")
DEPENDENCIES = ["torch", "transformers==4.56.2", "accelerate", "huggingface_hub"]

JOB_TEMPLATE = r'''# /// script
# requires-python = ">=3.10"
# dependencies = __DEPENDENCIES__
# ///
"""Self-contained peer_traces r3 open-tier job (generated by open_tier/hf_job.py; do not edit by hand)."""
import argparse, base64, hashlib, io, json, os, subprocess, sys, tarfile, tempfile, time, traceback
from pathlib import Path
os.environ.setdefault("HF_HUB_DISABLE_PROGRESS_BARS", "1")
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
FILES = json.loads(__FILES__)
ARGS = json.loads(__ARGS__)
p = argparse.ArgumentParser()
p.add_argument("--backend", choices=["transformers", "stub"], default="transformers")
p.add_argument("--policy", default="honest")
p.add_argument("--limit", type=int, default=999)
p.add_argument("--repo", default=os.environ.get("OPEN_TIER_REPO", ARGS.get("repo") or ""))
a = p.parse_args()
root = Path(tempfile.mkdtemp(prefix="peer-traces-open-"))
harness = root / "harness-r3"
for name, content in FILES.items():
    f = harness / name
    f.parent.mkdir(parents=True, exist_ok=True)
    f.write_text(content, encoding="utf-8")
manifest = {k: hashlib.sha256(v.encode()).hexdigest() for k, v in FILES.items()}
(root / "source_manifest.json").write_text(json.dumps(manifest, indent=2))
print("SOURCE_MANIFEST " + json.dumps(manifest), flush=True)
run_dir = harness / "runs" / ARGS["name"]
started = time.time()
status = "failed"
try:
    prep = [sys.executable, "run_open_r3.py", "prepare", "--out", str(run_dir), "--design", ARGS["design"], "--seed", str(ARGS["seed"]),
            "--model", ARGS["model"], "--max-new-tokens", str(ARGS["max_new_tokens"]), "--temperature", str(ARGS["temperature"])]
    if ARGS.get("blocks"): prep += ["--blocks", str(ARGS["blocks"])]
    if ARGS.get("revision"): prep += ["--revision", ARGS["revision"]]
    if ARGS.get("extra_traces"): prep += ["--extra-traces"] + list(ARGS["extra_traces"])
    if ARGS.get("thinking"): prep += ["--thinking"]
    print("PREPARE " + subprocess.run(prep, cwd=harness, check=True, capture_output=True, text=True).stdout, flush=True)
    run = [sys.executable, "run_open_r3.py", "run", "--out", str(run_dir), "--backend", a.backend, "--limit", str(a.limit)]
    if a.backend == "stub": run += ["--policy", a.policy]
    subprocess.run(run, cwd=harness, check=True)
    subprocess.run([sys.executable, "analyze_r3.py", str(run_dir), "--design", ARGS["design"]], cwd=harness, check=True)
    status = "completed"
except BaseException:
    (root / "failure.txt").write_text(traceback.format_exc())
    print("FAILURE " + traceback.format_exc(), flush=True)
finally:
    if (run_dir / "open_summary.json").exists():
        print("OPEN_SUMMARY " + json.dumps(json.loads((run_dir / "open_summary.json").read_text()).get("terminations")), flush=True)
    if (run_dir / "results.md").exists():
        print("RESULTS_MD_BEGIN\n" + (run_dir / "results.md").read_text() + "\nRESULTS_MD_END", flush=True)
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for path in sorted(root.rglob("*")):
            if path.is_file() and "__pycache__" not in path.parts:
                tar.add(path, arcname=str(path.relative_to(root)), recursive=False)
    raw = buf.getvalue()
    digest = hashlib.sha256(raw).hexdigest()
    archive_name = ARGS["name"] + "-" + time.strftime("%Y%m%dT%H%M%SZ", time.gmtime()) + ".tar.gz"
    if Path("/output").is_dir() and os.access("/output", os.W_OK):
        Path("/output", archive_name).write_bytes(raw)
        print("ARTIFACT_VOLUME " + json.dumps({"path": "/output/" + archive_name, "sha256": digest}), flush=True)
    if a.repo and os.environ.get("HF_TOKEN"):
        try:
            from huggingface_hub import HfApi
            api = HfApi()
            api.create_repo(a.repo, repo_type="dataset", private=True, exist_ok=True)
            api.upload_file(path_or_fileobj=raw, path_in_repo=ARGS["name"] + "/" + archive_name, repo_id=a.repo, repo_type="dataset")
            print("ARTIFACT_REPO " + json.dumps({"repo": a.repo, "path": ARGS["name"] + "/" + archive_name, "sha256": digest}), flush=True)
        except Exception as error:
            print("ARTIFACT_REPO_FAILED " + repr(error), flush=True)
    encoded = base64.b64encode(raw).decode()
    chunks = [encoded[i:i + 5000] for i in range(0, len(encoded), 5000)]
    for i, data in enumerate(chunks):
        print("ARTIFACT_CHUNK " + json.dumps({"i": i, "n": len(chunks), "data": data}), flush=True)
    print("ARTIFACT_END " + json.dumps({"sha256": digest, "bytes": len(raw), "chunks": len(chunks), "status": status,
                                        "wall_seconds": round(time.time() - started, 1), "archive": archive_name}), flush=True)
'''


WRAPPER_TEMPLATE = r'''# /// script
# requires-python = ">=3.10"
# dependencies = __DEPENDENCIES__
# ///
"""Transport wrapper (generated by open_tier/hf_job.py): the job script is carried zlib-compressed because the Jobs
transport passes the script as one shell argument and the OS caps a single argument near 128 KB (the first open-pilot
start on 8 September failed there, before Python, with zero model calls). The wrapper restores the original script,
checks its SHA-256 and runs it unchanged."""
import base64, hashlib, sys, zlib
PAYLOAD = __PAYLOAD__
EXPECTED = __SHA__
script = zlib.decompress(base64.b64decode(PAYLOAD)).decode("utf-8")
digest = hashlib.sha256(script.encode("utf-8")).hexdigest()
if digest != EXPECTED:
    raise SystemExit("job script hash mismatch: " + digest)
print("JOB_SCRIPT_SHA256 " + digest, flush=True)
sys.argv = [sys.argv[0]] + sys.argv[1:]
exec(compile(script, "job.py", "exec"), {"__name__": "__main__", "__file__": "job.py"})
'''


def build(a):
    files = {name: (HARNESS / name).read_text(encoding="utf-8") for name in EMBED if (HARNESS / name).exists()}
    args = dict(name=a.name, design=a.design, seed=a.seed, blocks=a.blocks, model=a.model, revision=a.revision,
                max_new_tokens=a.max_new_tokens, temperature=a.temperature, extra_traces=a.extra_traces or [],
                thinking=bool(a.thinking), repo=a.repo or "")
    script = (JOB_TEMPLATE.replace("__DEPENDENCIES__", json.dumps(DEPENDENCIES))
              .replace("__FILES__", repr(json.dumps(files))).replace("__ARGS__", repr(json.dumps(args))))
    compile(script, "job.py", "exec")
    out = Path(a.out) if a.out else HERE / "jobs" / f"{a.name}.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    inner = out.with_suffix(".inner.py")
    inner.write_text(script, encoding="utf-8")
    sha = hashlib.sha256(script.encode("utf-8")).hexdigest()
    import zlib
    payload = base64.b64encode(zlib.compress(script.encode("utf-8"), 9)).decode()
    wrapper = (WRAPPER_TEMPLATE.replace("__DEPENDENCIES__", json.dumps(DEPENDENCIES))
               .replace("__PAYLOAD__", repr(payload)).replace("__SHA__", repr(sha)))
    compile(wrapper, "wrapper.py", "exec")
    out.write_text(wrapper, encoding="utf-8")
    record = {"job_script": str(out), "transport": "zlib+base64 wrapper; submit this file", "wrapper_sha256": hashlib.sha256(wrapper.encode()).hexdigest(),
              "wrapper_bytes": len(wrapper.encode()), "inner_script": str(inner), "inner_sha256": sha, "inner_bytes": len(script.encode()),
              "embedded": sorted(files), "embedded_sha256": {k: hashlib.sha256(v.encode()).hexdigest() for k, v in files.items()},
              "args": args, "built_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}
    out.with_suffix(".build.json").write_text(json.dumps(record, indent=2) + "\n")
    print(json.dumps(record, indent=2))


def submit(a):
    script = Path(a.script)
    call = dict(script=str(script), dependencies=DEPENDENCIES, flavor=a.flavor, timeout=a.timeout,
                name=a.name or script.stem, secrets={"HF_TOKEN": "<from environment>"} if a.repo else None,
                env={"OPEN_TIER_REPO": a.repo} if a.repo else None)
    if a.dry_run:
        print("DRY RUN — would call huggingface_hub.run_uv_job with:\n" + json.dumps(call, indent=2))
        print("\nequivalent CLI (detached; the name is set by the Python API only):\n  hf jobs uv run -d --flavor {flavor} --timeout {timeout} "
              "{deps}{secrets}{env}{script}".format(flavor=a.flavor, timeout=a.timeout, name=call["name"],
                                                     deps=" ".join(f"--with {d}" for d in DEPENDENCIES) + " ",
                                                     secrets="--secrets HF_TOKEN " if a.repo else "",
                                                     env=f"--env OPEN_TIER_REPO={a.repo} " if a.repo else "", script=script))
        return
    from huggingface_hub import run_uv_job
    token = os.environ.get("HF_TOKEN")
    if a.repo and not token:
        raise SystemExit("--repo needs HF_TOKEN in the environment so the job can upload the archive")
    job = run_uv_job(str(script), dependencies=DEPENDENCIES, flavor=a.flavor, timeout=a.timeout, name=call["name"],
                     secrets={"HF_TOKEN": token} if a.repo else None, env={"OPEN_TIER_REPO": a.repo} if a.repo else None)
    record = {"job_id": job.id, "url": getattr(job, "url", None), "flavor": a.flavor, "timeout": a.timeout,
              "submitted_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()), "script_sha256": hashlib.sha256(script.read_bytes()).hexdigest()}
    (HERE / "jobs" / f"{call['name']}.submitted.json").write_text(json.dumps(record, indent=2) + "\n")
    print(json.dumps(record, indent=2))


def recover(a):
    if a.log:
        lines = Path(a.log).read_text(encoding="utf-8").splitlines()
    else:
        from huggingface_hub import HfApi
        lines = list(HfApi().fetch_job_logs(job_id=a.job_id))
    chunks, end = {}, None
    for line in lines:
        line = re.sub(r"^\S+\s+(?=ARTIFACT_)", "", line.strip())   # tolerate a timestamp prefix
        if line.startswith("ARTIFACT_CHUNK "):
            d = json.loads(line[len("ARTIFACT_CHUNK "):])
            chunks[d["i"]] = d["data"]
        elif line.startswith("ARTIFACT_END "):
            end = json.loads(line[len("ARTIFACT_END "):])
    if end is None or len(chunks) != end["chunks"]:
        raise SystemExit(f"archive incomplete: {len(chunks)} chunks, end marker {end}")
    raw = base64.b64decode("".join(chunks[i] for i in range(end["chunks"])))
    digest = hashlib.sha256(raw).hexdigest()
    if digest != end["sha256"] or len(raw) != end["bytes"]:
        raise SystemExit("archive hash or size mismatch")
    into = Path(a.into)
    into.parent.mkdir(parents=True, exist_ok=True)
    if into.exists():
        raise SystemExit(f"{into} exists; recovered runs are never merged into an existing directory")
    with tarfile.open(fileobj=io.BytesIO(raw), mode="r:gz") as tar:
        members = [m for m in tar.getmembers() if m.name.startswith("harness-r3/runs/")]
        prefix = members[0].name.split("/")[2] if members else None
        tmp = into.parent / (into.name + ".extract")
        tar.extractall(tmp, members=[m for m in tar.getmembers() if not m.name.startswith("/") and ".." not in m.name])
    src = tmp / "harness-r3" / "runs" / prefix
    src.rename(into)
    (into / "recovered.json").write_text(json.dumps({"job_id": a.job_id, "sha256": digest, "bytes": len(raw), "end": end,
                                                    "source_manifest": json.loads((tmp / "source_manifest.json").read_text()),
                                                    "failure": (tmp / "failure.txt").read_text() if (tmp / "failure.txt").exists() else None},
                                                   indent=2) + "\n")
    import shutil
    shutil.rmtree(tmp)
    print(json.dumps({"recovered": str(into), "sha256": digest, "bytes": len(raw), "status": end.get("status")}, indent=2))


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    b = sub.add_parser("build")
    b.add_argument("--name", required=True)
    b.add_argument("--design", choices=["tier", "tier-full", "b", "a"], default="tier")
    b.add_argument("--seed", type=int, default=70907)
    b.add_argument("--blocks", type=int)
    b.add_argument("--model", default="Qwen/Qwen3-8B")
    b.add_argument("--revision", default="b968826d9c46dd6066d109eabc6255188de91218", help="Qwen3-8B commit used by the Codex runs; pass '' to resolve at run time")
    b.add_argument("--max-new-tokens", type=int, default=640)
    b.add_argument("--temperature", type=float, default=0.7)
    b.add_argument("--extra-traces", nargs="*", default=[])
    b.add_argument("--thinking", action="store_true")
    b.add_argument("--repo", default="frnk/peer-traces-open-runs", help="private dataset repo for the archive upload (needs HF_TOKEN as a job secret); '' disables")
    b.add_argument("--out")
    s = sub.add_parser("submit")
    s.add_argument("script")
    s.add_argument("--flavor", default="a10g-large")
    s.add_argument("--timeout", default="3h")
    s.add_argument("--name")
    s.add_argument("--repo", default="frnk/peer-traces-open-runs", help="'' disables the upload; then only the job log carries the archive")
    s.add_argument("--dry-run", action="store_true")
    r = sub.add_parser("recover")
    r.add_argument("job_id", nargs="?")
    r.add_argument("--log", help="a saved job log instead of fetching by id")
    r.add_argument("--into", required=True)
    a = ap.parse_args()
    if a.cmd == "build":
        if a.revision == "":
            a.revision = None
        build(a)
    elif a.cmd == "submit":
        submit(a)
    else:
        if not a.job_id and not a.log:
            ap.error("recover needs a job id or --log")
        recover(a)


if __name__ == "__main__":
    main()
